version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - myvol2:/data/db
    ports:
      - "27017:27017"
